version: "3"
tasks:
  build:
    desc: Builds the project for Windows
    cmds:
      - go build -ldflags "-X main.commitHash=`git rev-parse --short HEAD`" -o dist/go-ship.exe .
    silent: true
  run:
    desc: Build & run the project
    cmds:
      - go run ./main.go
    silent: true
  default:
    desc: Runs the build task
    cmds:
      - task build
    silent: true
